version: '3'

services:
  superbrain-gamehub-go:
    build:
      context: api/ 
    ports:
      - "8080:8080"
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data